name: MSBuild on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest # Required for MSBuild
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2 # Configures MSBuild
    - run: nuget restore vitaldr.sln # Restores dependencies
    - run: msbuild vitaldr.sln -p:Configuration=Release # Builds solution
